In [9]:
import pandas as pd
p_0801 = pd.read_csv('C:/Users/DJA/Downloads/데이터/원본자료/새 폴더/pop_200801_200803_u8.csv')
get_idx = [0,16,17,18,19,20,21,22,23,53,54,55,56]
get_idx2 = [0,85,86,87,88,89,90,91,92,122,123,124,125]
get_idx3 = [0,154,155,156,157,158,159,160,161,191,192,193,194]
# get_idx = [0,16,17,18,19,20,21,22,23,53,54,55,56,85,86,87,88,89,90,91,92,122,123,124,125,154,155,156,157,158,159,160,161,191,192,193,194]
# get_idx.append(list(range(16,24)))
# for i in range(len(p_0801.columns)):
#     print(p_0801.columns[i])
# tp_0801 = p_0801[['행정구역','2008년01월_계_총인구수','2008년02월_계_총인구수','2008년03월_계_총인구수']]
# tpm_08_17 = p_0801[p_0801.columns[get_idx]]
pr_0801 = p_0801[p_0801.columns[get_idx]]
# p_0801[p_0801.columns[get_idx]]
# p_0801[p_0801.columns[get_idx2]].head()
# p_0801[p_0801.columns[get_idx3]].head()

SyntaxError: invalid syntax (<ipython-input-9-dd9f5d711cba>, line 17)

In [97]:
pr_0801['노인'] = pr_0801[pr_0801.columns[1:9]].sum(axis=1)
pr_0801.head()

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,행정구역,2008년01월_계_65~69세,2008년01월_계_70~74세,2008년01월_계_75~79세,2008년01월_계_80~84세,2008년01월_계_85~89세,2008년01월_계_90~94세,2008년01월_계_95~99세,2008년01월_계_100세 이상,2008년01월_여_20~24세,2008년01월_여_25~29세,2008년01월_여_30~34세,2008년01월_여_35~39세,노인
0,서울특별시 (1100000000),365485.0,226758.0,133121.0,74759.0,36508.0,11478.0,2406.0,401.0,362744.0,506536.0,465358.0,476819.0,850916.0
1,서울특별시 종로구 (1111000000),7850.0,5097.0,3062.0,1758.0,947.0,299.0,54.0,11.0,5912.0,7601.0,6391.0,7558.0,19078.0
2,서울특별시 종로구 청운동(1111051000),183.0,157.0,92.0,44.0,24.0,11.0,2.0,0.0,123.0,146.0,159.0,243.0,513.0
3,서울특별시 종로구 효자동(1111052000),575.0,382.0,213.0,129.0,69.0,22.0,6.0,1.0,387.0,516.0,533.0,594.0,1397.0
4,서울특별시 종로구 사직동(1111053000),495.0,323.0,209.0,117.0,59.0,18.0,1.0,1.0,292.0,388.0,360.0,429.0,1223.0

In [98]:
pr_0801['2030여성'] = pr_0801[pr_0801.columns[9:13]].sum(axis=1)
pr_0801.head()

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,행정구역,2008년01월_계_65~69세,2008년01월_계_70~74세,2008년01월_계_75~79세,2008년01월_계_80~84세,2008년01월_계_85~89세,2008년01월_계_90~94세,2008년01월_계_95~99세,2008년01월_계_100세 이상,2008년01월_여_20~24세,2008년01월_여_25~29세,2008년01월_여_30~34세,2008년01월_여_35~39세,노인,2030여성
0,서울특별시 (1100000000),365485.0,226758.0,133121.0,74759.0,36508.0,11478.0,2406.0,401.0,362744.0,506536.0,465358.0,476819.0,850916.0,1811457.0
1,서울특별시 종로구 (1111000000),7850.0,5097.0,3062.0,1758.0,947.0,299.0,54.0,11.0,5912.0,7601.0,6391.0,7558.0,19078.0,27462.0
2,서울특별시 종로구 청운동(1111051000),183.0,157.0,92.0,44.0,24.0,11.0,2.0,0.0,123.0,146.0,159.0,243.0,513.0,671.0
3,서울특별시 종로구 효자동(1111052000),575.0,382.0,213.0,129.0,69.0,22.0,6.0,1.0,387.0,516.0,533.0,594.0,1397.0,2030.0
4,서울특별시 종로구 사직동(1111053000),495.0,323.0,209.0,117.0,59.0,18.0,1.0,1.0,292.0,388.0,360.0,429.0,1223.0,1469.0

In [99]:
pr_0801['0801소멸비율'] = pr_0801['2030여성'] / (pr_0801['노인'] / 2)
pr_0801.head()

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,행정구역,2008년01월_계_65~69세,2008년01월_계_70~74세,2008년01월_계_75~79세,2008년01월_계_80~84세,2008년01월_계_85~89세,2008년01월_계_90~94세,2008년01월_계_95~99세,2008년01월_계_100세 이상,2008년01월_여_20~24세,2008년01월_여_25~29세,2008년01월_여_30~34세,2008년01월_여_35~39세,노인,2030여성,0801소멸비율
0,서울특별시 (1100000000),365485.0,226758.0,133121.0,74759.0,36508.0,11478.0,2406.0,401.0,362744.0,506536.0,465358.0,476819.0,850916.0,1811457.0,4.257664
1,서울특별시 종로구 (1111000000),7850.0,5097.0,3062.0,1758.0,947.0,299.0,54.0,11.0,5912.0,7601.0,6391.0,7558.0,19078.0,27462.0,2.878918
2,서울특별시 종로구 청운동(1111051000),183.0,157.0,92.0,44.0,24.0,11.0,2.0,0.0,123.0,146.0,159.0,243.0,513.0,671.0,2.615984
3,서울특별시 종로구 효자동(1111052000),575.0,382.0,213.0,129.0,69.0,22.0,6.0,1.0,387.0,516.0,533.0,594.0,1397.0,2030.0,2.906228
4,서울특별시 종로구 사직동(1111053000),495.0,323.0,209.0,117.0,59.0,18.0,1.0,1.0,292.0,388.0,360.0,429.0,1223.0,1469.0,2.402289

In [100]:
pr_0801 = pr_0801[pr_0801.columns[[0, -1]]]
pr_0801.head()

                        행정구역  0801소멸비율
0        서울특별시  (1100000000)  4.257664
1     서울특별시 종로구 (1111000000)  2.878918
2  서울특별시 종로구 청운동(1111051000)  2.615984
3  서울특별시 종로구 효자동(1111052000)  2.906228
4  서울특별시 종로구 사직동(1111053000)  2.402289

In [101]:
pr_0801a = p_0801[p_0801.columns[get_idx2]]
pr_0801a['노인'] = pr_0801a[pr_0801a.columns[1:9]].sum(axis=1)
pr_0801a['2030여성'] = pr_0801a[pr_0801a.columns[9:13]].sum(axis=1)
pr_0801a['0802소멸비율'] = pr_0801a['2030여성'] / (pr_0801a['노인'] / 2)
pr_0801a = pr_0801a[pr_0801a.columns[[0, -1]]]
pr_0801a.head()

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

                        행정구역  0802소멸비율
0        서울특별시  (1100000000)  4.225334
1     서울특별시 종로구 (1111000000)  2.873993
2  서울특별시 종로구 청운동(1111051000)  2.638132
3  서울특별시 종로구 효자동(1111052000)  2.877218
4  서울특별시 종로구 사직동(1111053000)  2.437002

In [102]:
pr_0801 = pd.merge(pr_0801,pr_0801a, how='outer')
pr_0801.head()

                        행정구역  0801소멸비율  0802소멸비율
0        서울특별시  (1100000000)  4.257664  4.225334
1     서울특별시 종로구 (1111000000)  2.878918  2.873993
2  서울특별시 종로구 청운동(1111051000)  2.615984  2.638132
3  서울특별시 종로구 효자동(1111052000)  2.906228  2.877218
4  서울특별시 종로구 사직동(1111053000)  2.402289  2.437002

In [103]:
y_f = '{0:02d}'
m_f = '{0:02d}'

for i in range(8,18):
    for j in range(1,11,3):
        p = pd.read_csv('C:/Users/DJA/Downloads/데이터/원본자료/새 폴더/pop_20'+
                        y_f.format(i)+m_f.format(j)+'_20'+y_f.format(i)+m_f.format(j+2)+'_u8.csv')
        p0 = p[p.columns[get_idx]]
        p1 = p[p.columns[get_idx2]]
        p2 = p[p.columns[get_idx3]]
        p0['노인'] = p0[p0.columns[1:9]].sum(axis=1)
        p1['노인'] = p1[p1.columns[1:9]].sum(axis=1)
        p2['노인'] = p2[p2.columns[1:9]].sum(axis=1)
        p0['2030여성'] = p0[p0.columns[9:13]].sum(axis=1)
        p1['2030여성'] = p1[p1.columns[9:13]].sum(axis=1)
        p2['2030여성'] = p2[p2.columns[9:13]].sum(axis=1)
        p0[y_f.format(i)+m_f.format(j)+'소멸비율'] = p0['2030여성'] / (p0['노인'] / 2)
        p1[y_f.format(i)+m_f.format(j+1)+'소멸비율'] = p1['2030여성'] / (p1['노인'] / 2)
        p2[y_f.format(i)+m_f.format(j+2)+'소멸비율'] = p2['2030여성'] / (p2['노인'] / 2)
        p0 = p0[p0.columns[[0, -1]]]
        p1 = p1[p1.columns[[0, -1]]]
        p2 = p2[p2.columns[[0, -1]]]
        p0 = pd.merge(p0, p1, how='outer')
        p0 = pd.merge(p0, p2, how='outer')
        pr_0801 = pd.merge(pr_0801, p0, how='outer')
pr_0801.head()

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Java\Python35\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,행정구역,0801소멸비율,0802소멸비율,0803소멸비율,0804소멸비율,0805소멸비율,0806소멸비율,0807소멸비율,0808소멸비율,0809소멸비율,...,1703소멸비율,1704소멸비율,1705소멸비율,1706소멸비율,1707소멸비율,1708소멸비율,1709소멸비율,1710소멸비율,1711소멸비율,1712소멸비율
0,서울특별시 (1100000000),4.257664,4.225334,4.189716,4.169195,4.151027,4.136442,4.117900,4.094905,4.069941,...,2.325830,2.317569,2.303019,2.295035,2.284388,2.274636,2.263960,2.252767,2.242796,2.228718
1,서울특별시 종로구 (1111000000),2.878918,2.873993,2.850645,2.851153,2.847277,2.853872,2.853100,2.844921,2.827049,...,1.760279,1.760016,1.751165,1.750088,1.745725,1.745106,1.743528,1.738360,1.737689,1.730849
2,서울특별시 종로구 청운동(1111051000),2.615984,2.638132,2.618110,2.595661,2.558594,2.593320,2.638889,2.741344,2.754098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울특별시 종로구 효자동(1111052000),2.906228,2.877218,2.824843,2.827634,2.847719,2.859958,2.861996,2.828070,2.790763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울특별시 종로구 사직동(1111053000),2.402289,2.437002,2.430360,2.480874,2.503106,2.501153,2.496933,2.505730,2.508706,...,1.672941,1.654321,1.640936,1.636790,1.653442,1.654407,1.648364,1.652835,1.639229,1.647821

In [104]:
pr_0801['지역'] = [i.split('(')[0] for i in pr_0801[pr_0801.columns[0]]]
pr_0801.head()

,행정구역,0801소멸비율,0802소멸비율,0803소멸비율,0804소멸비율,0805소멸비율,0806소멸비율,0807소멸비율,0808소멸비율,0809소멸비율,...,1704소멸비율,1705소멸비율,1706소멸비율,1707소멸비율,1708소멸비율,1709소멸비율,1710소멸비율,1711소멸비율,1712소멸비율,지역
0,서울특별시 (1100000000),4.257664,4.225334,4.189716,4.169195,4.151027,4.136442,4.117900,4.094905,4.069941,...,2.317569,2.303019,2.295035,2.284388,2.274636,2.263960,2.252767,2.242796,2.228718,서울특별시
1,서울특별시 종로구 (1111000000),2.878918,2.873993,2.850645,2.851153,2.847277,2.853872,2.853100,2.844921,2.827049,...,1.760016,1.751165,1.750088,1.745725,1.745106,1.743528,1.738360,1.737689,1.730849,서울특별시 종로구
2,서울특별시 종로구 청운동(1111051000),2.615984,2.638132,2.618110,2.595661,2.558594,2.593320,2.638889,2.741344,2.754098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 종로구 청운동
3,서울특별시 종로구 효자동(1111052000),2.906228,2.877218,2.824843,2.827634,2.847719,2.859958,2.861996,2.828070,2.790763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 종로구 효자동
4,서울특별시 종로구 사직동(1111053000),2.402289,2.437002,2.430360,2.480874,2.503106,2.501153,2.496933,2.505730,2.508706,...,1.654321,1.640936,1.636790,1.653442,1.654407,1.648364,1.652835,1.639229,1.647821,서울특별시 종로구 사직동

In [105]:
pr_0801['지역번호'] = [i.split('(')[1][:-1] for i in pr_0801[pr_0801.columns[0]]]
pr_0801.head()

,행정구역,0801소멸비율,0802소멸비율,0803소멸비율,0804소멸비율,0805소멸비율,0806소멸비율,0807소멸비율,0808소멸비율,0809소멸비율,...,1705소멸비율,1706소멸비율,1707소멸비율,1708소멸비율,1709소멸비율,1710소멸비율,1711소멸비율,1712소멸비율,지역,지역번호
0,서울특별시 (1100000000),4.257664,4.225334,4.189716,4.169195,4.151027,4.136442,4.117900,4.094905,4.069941,...,2.303019,2.295035,2.284388,2.274636,2.263960,2.252767,2.242796,2.228718,서울특별시,1100000000
1,서울특별시 종로구 (1111000000),2.878918,2.873993,2.850645,2.851153,2.847277,2.853872,2.853100,2.844921,2.827049,...,1.751165,1.750088,1.745725,1.745106,1.743528,1.738360,1.737689,1.730849,서울특별시 종로구,1111000000
2,서울특별시 종로구 청운동(1111051000),2.615984,2.638132,2.618110,2.595661,2.558594,2.593320,2.638889,2.741344,2.754098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 종로구 청운동,1111051000
3,서울특별시 종로구 효자동(1111052000),2.906228,2.877218,2.824843,2.827634,2.847719,2.859958,2.861996,2.828070,2.790763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 종로구 효자동,1111052000
4,서울특별시 종로구 사직동(1111053000),2.402289,2.437002,2.430360,2.480874,2.503106,2.501153,2.496933,2.505730,2.508706,...,1.640936,1.636790,1.653442,1.654407,1.648364,1.652835,1.639229,1.647821,서울특별시 종로구 사직동,1111053000

In [106]:
v_idx = [-1,-2]
# tp_08_17[tp_08_17.columns[[-1, -2]]].head()
for i in range(1,len(pr_0801.columns)-2):
    v_idx.append(i)

pr_08_17 = pr_0801[pr_0801.columns[v_idx]]
pr_08_17.head()

,지역번호,지역,0801소멸비율,0802소멸비율,0803소멸비율,0804소멸비율,0805소멸비율,0806소멸비율,0807소멸비율,0808소멸비율,...,1703소멸비율,1704소멸비율,1705소멸비율,1706소멸비율,1707소멸비율,1708소멸비율,1709소멸비율,1710소멸비율,1711소멸비율,1712소멸비율
0,1100000000,서울특별시,4.257664,4.225334,4.189716,4.169195,4.151027,4.136442,4.117900,4.094905,...,2.325830,2.317569,2.303019,2.295035,2.284388,2.274636,2.263960,2.252767,2.242796,2.228718
1,1111000000,서울특별시 종로구,2.878918,2.873993,2.850645,2.851153,2.847277,2.853872,2.853100,2.844921,...,1.760279,1.760016,1.751165,1.750088,1.745725,1.745106,1.743528,1.738360,1.737689,1.730849
2,1111051000,서울특별시 종로구 청운동,2.615984,2.638132,2.618110,2.595661,2.558594,2.593320,2.638889,2.741344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1111052000,서울특별시 종로구 효자동,2.906228,2.877218,2.824843,2.827634,2.847719,2.859958,2.861996,2.828070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1111053000,서울특별시 종로구 사직동,2.402289,2.437002,2.430360,2.480874,2.503106,2.501153,2.496933,2.505730,...,1.672941,1.654321,1.640936,1.636790,1.653442,1.654407,1.648364,1.652835,1.639229,1.647821

In [107]:
pr_08_17.to_csv('pr_monthly_08_17.csv',mode="w")